# This is a basic workflow to help you get started with Actions

name: Node.js CI

on:
  push:
    branches: [main, 218-criar-CI-CD]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PORT: 4040
      JWT_SECRET: 0a6b944d-d2fbtest
      MONGO_HOST: mongodb://127.0.0.1:27017/kilimpinho-backend
      MONGO_PORT: 27017
      EMAIL: admin@gmail.com

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: "16.14.2"

      - name: Install dependencies
        run: yarn install

      - name: Run test
        run: yarn test
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kilimpinho-backend"
          heroku_email: "kilimpinho.unb@gmail.com"
          branch: "218-criar-CI-CD"
          usedocker: true
          team: "2021.2_G2_Ki-Limpinho"
        env:
          MONGO_HOST: ${{secrets.MONGO_HOST}}
          NODE_ENV: production
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          EMAIL: ${{secrets.EMAIL}}
